language: erlang

env:
  - LUA=""

services:
  - cassandra

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - sudo apt-get install libreadline-dev libncurses5-dev libpcre3 libpcre3-dev libssl-dev perl make lua5.1 lua5.1-dev
  - wget http://openresty.org/download/ngx_openresty-1.7.7.2.tar.gz
  - tar xzf ngx_openresty-1.7.7.2.tar.gz
  - cd ngx_openresty-1.7.7.2/
  - ./configure
  - make
  - sudo make install
  - cd ..
  - export PATH=$PATH:/usr/local/openresty/nginx/sbin/
  - wget http://luarocks.org/releases/luarocks-2.2.0.tar.gz
  - tar xzf luarocks-2.2.0.tar.gz
  - cd luarocks-2.2.0
  - ./configure
  - make build
  - sudo make install
  - cd ..

install:
  - sudo make install

script: "make test-all"
