language: erlang

env:
  global:
    - LUAROCKS=2.2.0
    - OPENRESTY=1.7.7.2
    - CASSANDRA=2.1.2
  matrix:
    - LUA=lua5.1

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - bash .travis/setup_openresty.sh
  - export PATH=$PATH:/usr/local/openresty/nginx/sbin
  - bash .travis/setup_cassandra.sh

install:
  - sudo make install
  - sudo make dev

script: "make run-integration-tests COVERAGE_FLAG=--coverage FOLDER=spec"

after_success:
  - luacov-coveralls -i kong
