language: erlang

services:
  - cassandra

env:
  matrix:
    - LUA=lua5.1

branches:
  only:
    - master

before_install:
  - "bash .ci/setup_kong.sh"

install:
  - "sudo make dev"

script:
  - "busted -o spec/busted-print.lua --coverage spec/"
  - "make lint"

after_success: "luacov-coveralls -i kong"