source: ./app
destination: ./dist
plugins: ./app/_jekyll_plugins
exclude: ['node_modules', '.config']
keep_files: ['assets']
timezone: America/San_Francisco

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'

permalink: pretty
lsi: true
future: true

name: Kong by Mashape
domain: localhost:3000
url: http://localhost:9000
repo: https://github.com/Mashape/kong
