source: app
destination: .app
layouts: _layouts
exclude: ['node_modules', '.config']
keep_files: ['assets']
timezone: America/San_Francisco

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'

lsi: true
future: true

name: Kong by Mashape
domain: getkong.org
url: http://getkong.org
repo: https://github.com/Mashape/kong
