source: app
destination: .app
layouts: _layouts
exclude: ['node_modules', '.config']
keep_files: ['assets']
timezone: America/Toronto

collections:
  docs:
    output: true
    permalink: /docs/:path/

lsi: true
future: true
highligter: rouge
markdown: redcarpet

name: Kong by Mashape
twitter: mashape
domain: getkong.org
url: http://getkong.org
